name: Check Properties File

on:
  pull_request:
    paths:
      - '**.properties'

jobs:
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate properties files
        run: |
          FILES=$(find . -name "*.properties")
          for FILE in $FILES
          do
            while IFS= read -r LINE
            do
              if [[ ! $LINE =~ ^[a-zA-Z0-9.]*=.*$|^#.*$|^$ ]]; then
                echo "Syntax error in file $FILE: $LINE"
                exit 1
              fi
            done < "$FILE"
          done
